name: app_viajes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_indicator: ^1.0.6
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  go_router: ^15.1.1
  google_fonts: ^6.2.1
  google_generative_ai: ^0.4.7
  google_maps_flutter: ^2.12.2
  http: ^1.4.0
  intl: ^0.20.2
  lottie: ^3.3.1
  page_transition: ^2.2.1
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
