spring:
  application:
    name: travel
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.xml
    default-schema: travel
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10