spring:
  application:
    name: travel
  security:
    user:
      name: none
      password: none
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.xml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
gemini:
  url: getyourownapikeywinkwink;)