spring:
  application:
    name: travel
  security:
    user:
      name: none
      password: none
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.xml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
gemini:
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash?key=AIzaSyB_mmfa4J2TdW4atYzqi8DjDJv4wOodTkU