spring:
  application:
    name: travel
  security:
    user:
      name: none
      password: none
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.xml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:3648/postgres
    username: postgres
    password: ABCarturo200
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
gemini:
  url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash?key=AIzaSyDBMjetZ2-7ObKNnHy-WSk41YDKSeDRwm8